import Head from 'next/head'
import Navbar from 'ahmad/components/Navbar'
import { Inter } from '@next/font/google'
// import Herosection from 'components/Herosection/herosection'
import Footer from 'components/Footer/footer'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Navbar />
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Footer />
      <main>
        
      </main>
    </>

  )
}
